In [2]:
import pickle 
import os
from gensim.utils import SaveLoad
import tempfile


In [6]:
from gensim import corpora, models, similarities
loaded_lda_model = models.LdaModel.load('lda_model_final')

/Users/alxander44/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/smart_open/smart_open_lib.py:402: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [7]:
import pandas as pd

In [8]:
loaded_lda_model

In [9]:
jobs = pd.read_csv('/Users/alxander44/lda_test_10000.csv')

In [10]:
import pandas as pd 

In [11]:
jobs.head()

Unnamed: 0      0      1                                                  2
0           0  10001  10003  1. Job Description: In support of the DoD CIO ...
1           1  10002  10004  ## Overview\n\nAs a Lead Developer, you will l...
2           2  10003  10005  The Opportunity\n\nAs a member of our Data Sol...
3           3  10004  10006  Position Title: UiPath Developer \n\nRequired ...
4           4  10005  10007  Title: Android Developer\n\n  * H1b Status is ...

In [12]:
jobs = jobs.drop(columns=['Unnamed: 0','0','1'])

In [14]:
import numpy as np 
import gensim

from gensim.utils import simple_preprocess

def sentence_to_words(sentences):
    for sentence in sentences:
        yield(simple_preprocess(str(sentence), deacc=True)) 


In [15]:
data = jobs['2'].values.tolist()

In [259]:
type(data)

list

In [16]:
data_words = list(sentence_to_words(data)) # write a function takes in a list of a ton of des 

In [18]:
loaded_lda_model

In [19]:
import gensim.corpora as corpora

In [20]:
id2word=corpora.Dictionary.load('id2word')

/Users/alxander44/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/smart_open/smart_open_lib.py:402: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [21]:
#id2word = corpora.Dictionary(data_words)


corpus = [id2word.doc2bow(text) for text in data_words]

In [25]:
#empty_list = [x for x in range(17)]
#test = [loaded_lda_model[x][0][0] for empty_list in corpus[203]]


# run a loop for all the topic in a list 
# then run knn

In [120]:
des = []

for x in corpus:
    empty_list = [0 for _ in range(17)]
    test = loaded_lda_model.get_document_topics(x, minimum_probability=0, minimum_phi_value=0)
    for val in test:
        empty_list[val[0]-1] = val[1]
    des.append(empty_list[:])


In [121]:
df = pd.DataFrame(des)

In [160]:
df.head(10) # returns this data frame for the above des 

0         1         2         3         4         5         6   \
0  0.000822  0.000687  0.119798  0.000518  0.000461  0.144684  0.000378   
1  0.000378  0.000316  0.000271  0.383030  0.066966  0.208766  0.000174   
2  0.029187  0.000358  0.000307  0.000270  0.337929  0.142186  0.000197   
3  0.000674  0.000563  0.092639  0.075664  0.443309  0.297566  0.000310   
4  0.000852  0.000713  0.000613  0.718464  0.230976  0.000431  0.000392   
5  0.000459  0.000384  0.470744  0.000289  0.334218  0.000232  0.000211   
6  0.000962  0.000804  0.000691  0.000606  0.000540  0.424397  0.000443   
7  0.001424  0.001191  0.001024  0.000898  0.690930  0.166831  0.000656   
8  0.000938  0.000784  0.346056  0.123031  0.234677  0.290163  0.000432   
9  0.004499  0.003764  0.003235  0.238162  0.546654  0.002276  0.002071   

         7         8         9         10        11        12        13  \
0  0.000347  0.000320  0.000298  0.000278  0.729481  0.000246  0.000232   
1  0.000159  0.000147  0.000137  0.128500  0.210270  0.000113  0.000107   
2  0.120290  0.000167  0.022422  0.277546  0.000136  0.000128  0.000121   
3  0.000285  0.000263  0.000244  0.086686  0.000214  0.000201  0.000190   
4  0.000360  0.000333  0.033127  0.000289  0.000271  0.000255  0.000241   
5  0.000194  0.000179  0.022026  0.076322  0.000146  0.000137  0.000130   
6  0.179229  0.000375  0.000349  0.389043  0.000305  0.000288  0.000272   
7  0.131696  0.000556  0.000516  0.000482  0.000452  0.000426  0.000402   
8  0.000396  0.000366  0.000340  0.000317  0.000298  0.000280  0.000265   
9  0.001901  0.001756  0.001631  0.001524  0.001429  0.001346  0.001271   

         14        15        16  
0  0.000220  0.000209  0.001023  
1  0.000101  0.000096  0.000470  
2  0.000115  0.000109  0.068533  
3  0.000180  0.000171  0.000840  
4  0.000228  0.000217  0.012240  
5  0.000123  0.000117  0.094089  
6  0.000257  0.000245  0.001195  
7  0.000381  0.000362  0.001773  
8  0.000251  0.000239  0.001168  
9  0.181734  0.001145  0.005603

0         1         2         3         4         5         6   \
0  0.583238  0.011759  0.010108  0.008864  0.313698  0.007113  0.006473   

         7         8         9         10        11        12        13  \
0  0.005939  0.005487  0.005098  0.004761  0.004466  0.004205  0.003973   

         14        15        16  
0  0.003765  0.003578  0.017473

In [89]:
import numpy as np 
import pandas as pd

import scipy 
import matplotlib.pyplot as plt

import urllib
import sklearn 
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from sklearn import preprocessing 
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn import metrics

In [95]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [92]:
np.set_printoptions(precision=4, suppress = True)
%matplotlib inline
rcParams['figure.figsize'] =7,4
plt.style.use('seaborn-whitegrid')

In [123]:
 from sklearn.neighbors import NearestNeighbors


In [201]:
NN = NearestNeighbors(n_neighbors=17)

In [202]:
NN.fit

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=17, p=2, radius=1.0)


In [178]:
NN2 = NearestNeighbors(n_neighbors=17, algorithm='kd_tree')

In [206]:
NN2.fit(df)

NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=17, p=2, radius=1.0)

In [207]:
NN.fit(df)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=17, p=2, radius=1.0)

In [182]:
NN.kneighbors([df.loc[1075]], 10)

(array([[0.        , 0.04937257, 0.063936  , 0.09205354, 0.09774586,
         0.10754676, 0.1218442 , 0.14603893, 0.1483975 , 0.14935984]]),
 array([[1075, 1670, 8436, 4401, 8411, 5718, 6951, 5615, 1607, 4496]]))

In [183]:
NN2.kneighbors([df.loc[1075]], 10)

(array([[0.        , 0.04937257, 0.063936  , 0.09205354, 0.09774586,
         0.10754676, 0.1218442 , 0.14603893, 0.1483975 , 0.14935984]]),
 array([[1075, 1670, 8436, 4401, 8411, 5718, 6951, 5615, 1607, 4496]]))

In [197]:
data_test = ['Data Scientist with python background']
data_test = list(sentence_to_words(data_test))
data_test = [id2word.doc2bow(text) for text in data_test]
data_test_result = loaded_lda_model.get_document_topics(data_test[0], minimum_probability=0, minimum_phi_value=0)

In [204]:
empty_list = [0 for _ in range(17)]

for val in data_test_result:
        empty_list[val[0]-1] = val[1]
        

In [208]:
NN.kneighbors([empty_list],5)

(array([[0.10552986, 0.11056247, 0.11180526, 0.11285499, 0.11432841]]),
 array([[2493, 2709,  182, 2543, 2724]]))

In [377]:

    
""" Creating a function that take descriptions and returns the Topic Probability distrubution """
def des_to_topiclist(data):
    des = []
    """ creating a function that """
    def sentence_to_words(sentences):
        for sentence in sentences:
            yield(simple_preprocess(str(sentence), deacc=True)) 
    """ Preprocessing the data from a str to a list of list then passing it through the id2word model"""
    data = list(sentence_to_words(data))
    corpus = [id2word.doc2bow(text) for text in data]
    for x in corpus:
        """ Looping through the corpus to get the probability distrubution for each topic """
        empty_list = [0 for _ in range(17)]
        test = loaded_lda_model.get_document_topics(x, minimum_probability=0, minimum_phi_value=0)
        """ Creating a DataFrame for the job description and the probability distrubutioin of the topics"""
        for val in test:
            empty_list[val[0]-1] = val[1]          
        des.append(empty_list[:])
    return pd.DataFrame(des)

In [382]:
word_tests = ['i really like data science and python sql ad machine learning engineering ']
word_tests = des_to_topiclist(word_tests)


In [383]:
word_tests

0         1         2         3         4         5         6   \
0  0.41018  0.008553  0.183026  0.006447  0.339174  0.005173  0.004708   

         7        8         9         10        11        12        13  \
0  0.004319  0.00399  0.003708  0.003463  0.003248  0.003058  0.002889   

         14        15        16  
0  0.002738  0.002602  0.012723

In [384]:
NN2.kneighbors(word_tests)

(array([[0.1248403 , 0.1316549 , 0.17294988, 0.1781792 , 0.18533511,
         0.20180628, 0.20561909, 0.21000774, 0.21068721, 0.21684125,
         0.21866874, 0.22090856, 0.22140654, 0.2228301 , 0.22366932,
         0.22419892, 0.22605384]]),
 array([[7565, 7300, 2608, 7446, 3028, 4993, 7030,  273, 7908, 6986, 2464,
         2627, 7307, 2465, 7322, 7460, 7738]]))

In [385]:
data[7565]

'A bit about us:  \n\nBased inOrange County, CA we are a continually growing company in the AV (Audio / Video) Industry. We are the leading developer and manufacturer of professional AV system products. Our products are used worldwide in Business Boardrooms, University Halls, Training Centers, Government Offices, etc.   \n\nIf you are a Business Intelligence Developer with strong quantitative and analytical abilities, then please read on….  \n\nYou will be responsible for designing, building and deploying BI solutions for the companies objectives. Monitor and maintain BI and ETL processes and provide support as needed.\n\nWhat can we do for you?   \n\n  * Competitive Base Salary!  \n\n  * Excellent Benefits!  \n\n  * Continuous on the Job Training!  \n\n  * Accelerated Career Growth!  \n\nIs your background a fit? We are looking for…  \n\n  * Bachelors Degree in Computer Science or related degree  \n\n  * Experience enhancing, supporting and maintaining BI and Data Warehouse solutions\

In [138]:
import pickle

In [139]:
with open('Nearest_Neighbors_model', 'wb') as f:
    pickle.dump(NN,f)

In [214]:
with open('Nearest_Neighbors_model', 'rb') as f:
    NN_model = pickle.load(f)

In [217]:
NN_model.kneighbors([df.loc[44]], 3)

(array([[0.        , 0.03291856, 0.04572103]]), array([[  44, 6896, 2231]]))